project:
  type: website
  preview:
    port: 4000
  output-dir: docs

website:
  title: "CarpentriesOffline"
  description: "CarpentriesOffline Website"
  site-url: "https://carpentriesoffline.org/new_website_quarto/"
  page-navigation: true
  back-to-top-navigation: true
  favicon: images/favicon.ico
  repo-url: https://github.com/carpentriesoffline/new_website_quarto
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    logo: images/OFFLINE_logo.png
    logo-href: https://carpentriesoffline.org/new_website_quarto
    logo-alt: "CarpentriesOffline web page and documentation"
    title: CarpentriesOffline
    collapse-below: lg
    tools:
    - icon: github
      href: https://github.com/carpentriesoffline
    right:
      - text: Projects
        href: projects/index.qmd
        aria-label: Project Descriptions
      - text: Documentation
        href: documentation/index.qmd
      - text: Lessons
        href: lessons/index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - assets/theme-light.scss
    css: assets/nhsr.css
    code-link: true
    link-external-newwindow: true
    toc: true

execute:
  freeze: auto
