project:
  type: website
  preview:
    port: 4000
  output-dir: docs

website:
  title: "The Carpentries Offline"
  description: "CarpentriesOffline Website"
  site-url: "https://carpentriesoffline.org/"
  page-navigation: true
  back-to-top-navigation: true
  favicon: images/favicon.ico
  repo-url: https://github.com/carpentriesoffline/new_website_quarto/
  repo-actions: [edit, issue]
  navbar:
    background: primary
    toggle-position: right
    # logo: images/OFFLINE_logo.png
    logo-href: https://carpentriesoffline.org/
    logo-alt: "CarpentriesOffline web page and documentation"
    title: "The Carpentries Offline"
    tools:
    - icon: github
      href: https://github.com/carpentriesoffline/new_website_quarto/
    right:
      - text: "Projects"
        href: projects/index.qmd
        aria-label: Project Descriptions
      - text: "Documentation"
        href: documentation/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Lessons"
        href: lessons/index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - assets/theme-light.scss
    css: assets/nhsr.css
    code-link: true
    link-external-newwindow: true
    toc: true

execute:
  freeze: auto
